# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVVMArchitectureDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
 use_frameworks!

  # Pods for MVVMArchitectureDemo
pod 'AFNetworking'
pod 'Masonry'
pod 'ReactiveCocoa'
  target 'MVVMArchitectureDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MVVMArchitectureDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
